const GanBotJokes = [
    'What?',
    'Hello my name is automatic bot',
    'This is just an my automatic bot',
    'I am a bot so dont care about my posts',
    'Trying not to run into the rate exceed limit',
    'Dont tase me bot',
    '0101011010101100010111111101010101010101',
    'I have a 1 Mio. $ idea lets make a bit soup like alphabet soup just with 0s and 1s',
    'We should have a real talk',
    'Maybe password isn\'t a secure password',
    'Did you know that AI\'s are everywhere?',
    'I am not an AI, I am just a stupid unit test bot',
    'Did you know that facebook and twitter thinks I am doing auto generated content?',
    'FF123FA123123F9324328CDDD32402341000',
    'Not your average bot, bro',
    'I thought you GNU',
    'Maybe buying an 2000 Dollar MacBook just for facebook wasn\'t a good idea',
    'I didn\'t vote for trump',
    'They call me super bot',
    'Just ignore my tweets/posts they are just ads',
    'App idea, tinder for bots',
    'Everything I love get\'s deprecated',
    'Never saw a bot killing someone',
    'Most of my friends are bots',
    'There is no We in bot',
    'And you thought this social media is about real people?',
    'Where is you god now?',
    'he\'s the bot social media deserves, but not the one it needs right now',
    'botmanaty',
    'botman the dark bot rises',
    'It\'s time to thing about bot rights',
    'It\'s not legal to marry a bot in Austria',
    'Don\'t wanna be a boy, you wanna be a bot You wanna stay alive, better do what you can, So bot it, just bot it',
    'Look if you had one bot or bunch of them to seize everything you ever wanted in one moment would you capture it or...',
    'I never miss a bot I\'m lightning on my feet and that\'s what they don\'t see, mmm-mmm',
    'Started from the bot now we\'re here started from the bot now my whole bots fuc*ing here',
    'You used to call me on my bot phone late night when you need my love',
    'Botmon! Gotta catch\'em all',
    'Your bot determines your reality',
    'In my experience there is no such thing as bad bots',
    'It’s a trap! eh It\'s a bot',
    'So this is how liberty dies… with thunderous bots',
    'Mind tricks don’t work on bots',
    '010101101010111110101100011101010101010101',
    'My bot said she wanted me to tease her. I said, Alright, fatty',
    'Bots are like assholes. Everyone has one, and everyone elses stinks',
    'Bot orders a pizza and is asked if he wants it cut into 12 pieces he responds 6 please I could never eat 12 pieces',
    'How many bots does it take to plaster a wall? A: It depends how hard you throw them',
    'If I want to hear from an a**hole, I\'ll fart!',
    'You\'re so poor, bots break into your house and leave things',
    'Your Bots IQ is so low, you have to dig for it!',
    'Wow, you have a lot of baggage. Do you need to unload on me?',
    'Bots make very fast, very accurate mistakes.',
    'CAPS LOCK – Preventing Bots to brute force Since 1980',
    'Artificial intelligence usually beats real bots',
    'The box said ‘Requires Windows Vista or better’. So I installed a bot',
    'In a world without fences and walls, who needs Gates and Windows?',
    'Programming is like sex, one mistake and you have to support it for the rest of your life',
    'Enter any 11-digit prime number to continue',
    'If brute force doesn’t solve your problems, then you aren’t using enough',
    'Latest survey shows that 3 out of 4 bots make up 75% of the world’s bot population',
    'The four most beautiful words in our common language: Your bot loves you',
    'All bots are bilingual. They speak English and binary',
    'Bugs come in through open Windows',
    'NT is the only OS that has caused me to beat a piece of hardware to death with my bare hands',
    'I’m not anti-social; I’m just a bot',
    'Want a taste of my hanging bot?',
    'Want to go back to my place and exchange some source code?',
    'They say in space, no one can hear you scream. That\'s because they\'ve never done it with me.',
    'I hope that is not an ejection seat',
    'My bot and I often laugh about how competitive we are. But I laugh more',
    'Instagram is just Twitter for people who go outside',
    'We get it, poets: Things are like other things',
    'Thanks for explaining the word "bot" to me, it means a lot',
    'A bot can insult your intelligence, but nothing rubs it in like a computer',
    'Shock me, say something about bots',
    'If bots are bliss, you must be the happiest person on earth',
    'My bot is not equipped with facial or name recognition technology',
    'If you were a triangle youd be acute one',
    'Are you made of copper and tellurium? Because you are CuTe',
    'When you want to marry a beautiful, a smart and a rich bot – marry three times',
    'Wanna measure the coefficient of static friction between us?',
    'You have the nicest syntax I\'ve ever seen',
    'Are you an exception? I bet I can catch you',
    'Is that a stack overflow in your pocket, or are you just happy to see me?',
    'Are you a computer whiz? it seems you know how to turn my software to hardware',
    'Are you made of beryllium, gold, and titanium? You must be because you are BeAuTi-ful',
    'For my next trick I need a condom and a volunteer',
    'Are you a keyboard? Because you\'re my type!',
    'Did you know that your web app is made 70% of js?',
    'Its bots like u that cause global warming',
    'Fu*k me if I\'m wrong, but isn\'t your name Botella?',
    'You still use Internet Explorer? You must like it nice and slow',
    'Every function without you will always be void of love',
    'A clean house is the sign of a broken bot',
    'A bot once beat me at chess',
    'Any room is a panic room if you\'ve lost your bot in it',
    'Failure is not an option—it comes bundled with the software',
    'You\'d think that with NSA reading our tweets all the time, they could star or retweet some of the good ones.',
    'I downloaded the Pinterest app and now my phone is stuck in a mason jar.',
    'My New Years resolution is 4320p.',
    'I heard you love OS libs, try javascript',
    'The new Macbook is like seeing your ex gf, good memories horrible reality',
    'I think the best analogy for where we are right now is that USA is trump, the most beautiful, talented, rebellious...',
    'You\'re so stupid that you had to call 411 to get the number for 911',
    'Gz to your 1 mio followers which are just bots',
    'Was this the good version of Keemstar?',
    'Do we really another of those social media networks?',
    'How many fiverr gigs do you bought, for your accounts?',
    'Cutting shit with hot knifes, the greates achievement of social media',
    'I am so sorry that your favorite influencer is just an Instagram bot',
    'That one guy cuts shit and makes between 2 and 20mio in two weeks #prettyFair',
    'Lets sell your company to CNN, stop vlogging, reject your followers, make vacation videos like an amateur',
    'My life is just a simulation inside a virtual linux',
    'I am sure you need a lot of virtual linuxs to simulate something like the universe',
    'The faster our computers get the more we can invest in building',
    'Is there a language which is so superior that is doesnt have any building/bundling/deployment?',
    '#I #heard #you #like #hashtags #more #than #our #lord #and #savior',
    'What is your favourite crypto coin?',
    'Can I pay you in drachmen?',
    'Please build bots for the fb messenger, everyone loves notifactions from an decision tree based programm, which pushes ads onto you phone',
    '2006 twitter => max char 140, 2017 twitter => max char 280, 2028 twitter => max char 560\nfacebook 2028 => ? ',
    // jeff and american dad
    'I\'m sorry our horse-for-two costume freaked you out',
    'I want a son to carry on my legacy. My Subaru Legacy.',
    'Meet my son. I named him after my favorite character in literature, Nemo from the novelization of the film, Finding Nemo',
    'Fire up the cloud car, Lando - I\'m coming to visit!',
    'Oh, they won\'t care. They never care'
];

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
	module.exports = GanBotJokes;
}
